import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

def generate_incident_pdf(incidents, output_path):
    doc = SimpleDocTemplate(
        output_path, 
        pagesize=letter, 
        rightMargin=30, leftMargin=30, topMargin=30, bottomMargin=30
    )
    elements = []
    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=18,
        textColor=colors.HexColor('#0f172a'),
        spaceAfter=4
    )
    
    subtitle_style = ParagraphStyle(
        'SubTitleStyle',
        parent=styles['Normal'],
        fontSize=9,
        textColor=colors.HexColor('#64748b'),
        spaceAfter=15
    )
    
    insight_style = ParagraphStyle(
        'InsightStyle',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.HexColor('#0f172a'),
        alignment=0,
        leading=10
    )
    
    elements.append(Paragraph("CyberScope-AI: 7D Security Compliance Report", title_style))
    elements.append(Paragraph("Official export generated by Security Operations Center (SOC) Engine", subtitle_style))
    elements.append(Spacer(1, 10))
    
    # Updated headers for 7D
    data = [["ID", "Sensor", "H/W", "CPU", "Timestamp", "AI Threat Insight"]]
    
    for inc in incidents[::-1]:
        data.append([
            f"INC-00{inc[0]}",
            str(inc[1]),
            f"{inc[2]}C/{inc[3]}V",   # Combining Temp and Volt
            f"{inc[4]}%",             # CPU Util
            str(inc[9]).replace('T', ' ')[:19], # Index 9
            Paragraph(str(inc[10]), insight_style) # Index 10
        ])
        
    t = Table(data, colWidths=[40, 60, 60, 45, 100, 245])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1e293b')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 8),
        ('BOTTOMPADDING', (0,0), (-1,0), 6),
        ('TOPPADDING', (0,0), (-1,0), 6),
        ('BACKGROUND', (0,1), (-1,-1), colors.HexColor('#f8fafc')),
        ('TEXTCOLOR', (0,1), (-1,-1), colors.HexColor('#0f172a')),
        ('FONTNAME', (0,1), (-1,-1), 'Helvetica'),
        ('FONTSIZE', (0,1), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    
    elements.append(t)
    doc.build(elements)